xcopy /y "..\dlls"  "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"
xcopy /y /e /i "..\data\*"  "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug\data"

xcopy /y "..\submodules\vcpkg\packages\abseil_x64-windows\debug\bin\*.dll" "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"
xcopy /y "..\submodules\vcpkg\packages\c-ares_x64-windows\debug\bin\*.dll" "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"
xcopy /y "..\submodules\vcpkg\packages\curl_x64-windows\debug\bin\*.dll" "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"
xcopy /y "..\submodules\vcpkg\packages\openssl-windows_x64-windows\debug\bin\*.dll" "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"
xcopy /y "..\submodules\vcpkg\packages\protobuf_x64-windows\debug\bin\*.dll" "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"
xcopy /y "..\submodules\vcpkg\packages\re2_x64-windows\debug\bin\*.dll" "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"
xcopy /y "..\submodules\vcpkg\packages\zlib_x64-windows\debug\bin\*.dll" "..\..\build-CEECAM_Toolkit-Desktop_Qt_5_15_1_MSVC2019_64bit-Debug\debug"